server {
    listen       8080;
    server_name  localhost;

    # Root directory for Healthfo
    root   /usr/share/nginx/html;
    index  index.html;

    # Support for modular folder structure
    location / {
        try_files $uri $uri/ =404;
    }

    # Cache Control for static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Error handling
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
